# Generated by Django 3.2 on 2021-05-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0004_auto_20210501_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaznik',
            name='program',
            field=models.CharField(choices=[('zlaty', 'Zlatý program'), ('platinovy', 'Platinový program'), ('--', 'Běžný zákazník')], default='--', max_length=12),
            preserve_default=False,
        ),
    ]
